name: Build and Deploy Portfolio to GitHub Pages

on: [push]
permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Build 🔧
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
